feat!: organized arguments

diff --git a/post-cdash-status b/post-cdash-status
--- a/post-cdash-status
+++ b/post-cdash-status
@@ -3,34 +3,28 @@
 set -eo pipefail
 
 readonly API_BASE="https://api.github.com/repos/${GITHUB_REPOSITORY}"
-readonly TOKEN="${CI_GITHUB_ROBOT_TOKEN}"
-readonly COMMIT="${COMMIT_SHA}"
-readonly CDASH_PROJECT="${CDASH_PROJECT}"
-readonly STATUS_NAME="${CDASH_STATUS_NAME}"
-readonly BASE_URL="${CDASH_BASE_URL}"
 
-#==============================================================================
-
-function build_status_body() {
-  cat <<EOF
-{
-  "state": "success",
-  "target_url": "${BASE_URL}/index.php?compare1=61&filtercount=1&field1=revision&project=${CDASH_PROJECT}&showfilters=0&limit=100&value1=${COMMIT}&showfeed=0",
-  "description": "Build and test results available on CDash",
-  "context": "${STATUS_NAME}"
+function require_cmd() {
+  command -v "${1}" &> /dev/null || { echo "${1} not found"; exit 1; }
 }
-EOF
+
+function require_env_var() {
+  if [ -z "${!1}" ]; then
+    echo "${1} env variable empty"
+    exit 2
+  fi
 }
 
 #==============================================================================
 
-command -v curl &> /dev/null || { echo "curl not found"; exit 1; }
-command -v jq &> /dev/null || { echo "jq not found"; exit 2; }
-
-[ -z "${CI_GITHUB_ROBOT_TOKEN}" ] && { echo "CI_GITHUB_ROBOT_TOKEN env variable empty"; exit 3; }
-[ -z "${COMMIT_SHA}" ] && { echo "COMMIT_SHA env variable empty"; exit 4; }
-[ -z "${GITHUB_REPOSITORY}" ] && { echo "GITHUB_REPOSITORY env variable empty"; exit 5; }
-[ -z "${CDASH_PROJECT}" ] && { echo "CDASH_PROJECT env variable empty"; exit 6; }
+require_cmd "curl"
+require_cmd "jq"
+require_env_var "CDASH_BASE_URL"
+require_env_var "CDASH_PROJECT"
+require_env_var "COMMIT_SHA"
+require_env_var "GITHUB_REPOSITORY"
+require_env_var "GITHUB_STATUS_NAME"
+require_env_var "GITHUB_TOKEN"
 
 #==============================================================================
 
@@ -38,19 +32,28 @@ statuses=$(curl -q -s \
                 -H "Content-Type: application/json" \
                 -H "Accept: application/vnd.github+json" \
                 -H "X-GitHub-Api-Version: 2022-11-28" \
-                "${API_BASE}/commits/${COMMIT}/statuses" |\
+                "${API_BASE}/commits/${COMMIT_SHA}/statuses" |\
                 jq -r '[.[].context] | @json')
 
-if jq -re "all(. != \"cdash\")" <<<"${statuses}"; then
-  echo "Need to post a status for context cdash"
+post_body="$(cat<<EOF
+{
+  "state": "success",
+  "target_url": "${CDASH_BASE_URL}/index.php?compare1=61&filtercount=1&field1=revision&project=${CDASH_PROJECT}&showfilters=0&limit=100&value1=${COMMIT_SHA}&showfeed=0",
+  "description": "Build and test results available on CDash",
+  "context": "${GITHUB_STATUS_NAME}"
+}
+EOF
+)"
 
-  postBody="$(build_status_body)"
-  postUrl="${API_BASE}/statuses/${COMMIT}"
+post_url="${API_BASE}/statuses/${COMMIT_SHA}"
+
+if jq -re "all(. != \"${GITHUB_STATUS_NAME}\")" <<<"${statuses}"; then
+  echo "Need to post a status for context ${GITHUB_STATUS_NAME}"
 
   curl -X POST -q -s \
-       -H "Authorization: Bearer ${TOKEN}" \
+       -H "Authorization: Bearer ${GITHUB_TOKEN}" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
-       -d "${postBody}" "${postUrl}"
+       -d "${post_body}" "${post_url}"
 fi
